/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework2;

/**
 *
 * @author Msi
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gfd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        boname = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        bodate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        borrow = new javax.swing.JTextField();
        ret = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        re = new javax.swing.JButton();
        add = new javax.swing.JButton();
        book = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        gfd.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book name", "Borrow Date", "Borrower name", "Due date"
            }
        ));
        jScrollPane1.setViewportView(table);

        gfd.add(jScrollPane1);
        jScrollPane1.setBounds(390, 0, 490, 400);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Adding Books");
        gfd.add(jLabel1);
        jLabel1.setBounds(40, 30, 200, 20);
        gfd.add(boname);
        boname.setBounds(170, 180, 120, 26);

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        gfd.add(n);
        n.setBounds(170, 80, 120, 26);
        gfd.add(bodate);
        bodate.setBounds(170, 130, 120, 26);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gfd.add(jButton1);
        jButton1.setBounds(210, 520, 90, 30);

        bo.setText("Mark as Borrowed");
        bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boActionPerformed(evt);
            }
        });
        gfd.add(bo);
        bo.setBounds(110, 400, 140, 27);

        jLabel5.setText("Borrowing a book");
        gfd.add(jLabel5);
        jLabel5.setBounds(40, 370, 120, 20);

        jLabel6.setText("Returniing a book");
        gfd.add(jLabel6);
        jLabel6.setBounds(40, 440, 120, 16);

        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });
        gfd.add(borrow);
        borrow.setBounds(190, 360, 120, 26);
        gfd.add(ret);
        ret.setBounds(180, 440, 120, 26);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        gfd.add(exit);
        exit.setBounds(100, 520, 76, 27);

        re.setText("Mark as returned");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        gfd.add(re);
        re.setBounds(110, 480, 140, 27);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        gfd.add(add);
        add.setBounds(130, 280, 76, 27);

        book.setText("Book Name");
        gfd.add(book);
        book.setBounds(40, 90, 90, 16);

        jLabel3.setText("Borrowing Date");
        gfd.add(jLabel3);
        jLabel3.setBounds(40, 130, 130, 16);

        jLabel7.setText("Borrower Name");
        gfd.add(jLabel7);
        jLabel7.setBounds(40, 180, 100, 16);

        jLabel8.setText("Due Date");
        gfd.add(jLabel8);
        jLabel8.setBounds(40, 220, 110, 16);
        gfd.add(duedate);
        duedate.setBounds(170, 220, 120, 26);

        jPanel1.add(gfd);
        gfd.setBounds(20, 90, 890, 560);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome To The Library");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 350, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boname.setText("");

        bodate.setText("");
        n.setText("");
        borrow.setText("");
        ret.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    
      String name = n.getText().trim();
    String boDate = bodate.getText().trim();
      String boName = boname.getText().trim();
    String dueDate = duedate.getText().trim();
    
    model.addRow(new Object[]{name, boDate, boName, dueDate});
    
    n.setText("");
    bodate.setText("");
    boname.setText("");
    duedate.setText("");

    }//GEN-LAST:event_addActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
    }//GEN-LAST:event_borrowActionPerformed

    private void boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boActionPerformed
    String name = borrow.getText().trim();
        if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a name to borrow!");
        return;
    }
        DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.addRow(new Object[]{name, "Borrowed"});
        borrow.setText("");
                                
    }//GEN-LAST:event_boActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
    String name = ret.getText().trim();
    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a name!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        Object cellValue = model.getValueAt(i, 0);  // Get value safely
        if (cellValue != null && name.equals(cellValue.toString())) {
            model.setValueAt("Returned", i, 1);
            ret.setText("");
            return;
        }
    }
    JOptionPane.showMessageDialog(this, "Name not found!");

    }//GEN-LAST:event_reActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton bo;
    private javax.swing.JTextField bodate;
    private javax.swing.JTextField boname;
    private javax.swing.JLabel book;
    private javax.swing.JTextField borrow;
    private javax.swing.JTextField duedate;
    private javax.swing.JButton exit;
    private javax.swing.JPanel gfd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JButton re;
    private javax.swing.JTextField ret;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
