/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework2;

/**
 *
 * @author Msi
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public  signup() {
        initComponents();
                    this.setFocusable(true);
  
entern.setText("User name");
enterp.setText("Pasword");
enteri.setText("Insure Pasword");
entere.setText("Example.com");
    // For password fields, show the placeholder as regular text
    enterp.setEchoChar((char)0);
    enteri.setEchoChar((char)0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ch = new javax.swing.JComboBox<>();
        create = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        entern = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        entere = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enterp = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        enteri = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        ch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(ch);
        ch.setBounds(170, 390, 76, 26);

        create.setText("Create Account");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create);
        create.setBounds(410, 370, 116, 27);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(70, 390, 76, 27);

        signin.setText("Sign in");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin);
        signin.setBounds(330, 370, 76, 27);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome To The Library");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 350, 30);

        jPanel2.setLayout(null);

        entern.setText("Davied Jorge Klirck");
        entern.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enternFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enternFocusLost(evt);
            }
        });
        entern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enternActionPerformed(evt);
            }
        });
        jPanel2.add(entern);
        entern.setBounds(170, 30, 178, 26);

        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 30, 103, 27);

        entere.setText("Davidjorge@gmail.com");
        entere.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entereFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entereFocusLost(evt);
            }
        });
        entere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entereActionPerformed(evt);
            }
        });
        jPanel2.add(entere);
        entere.setBounds(170, 80, 170, 26);

        jLabel4.setText("Emain");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 80, 103, 16);

        enterp.setText(",kmjhngbfd");
        enterp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterpFocusLost(evt);
            }
        });
        enterp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpActionPerformed(evt);
            }
        });
        jPanel2.add(enterp);
        enterp.setBounds(170, 140, 170, 26);

        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 140, 103, 21);

        enteri.setText("nhgbfvdcs");
        enteri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enteriFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enteriFocusLost(evt);
            }
        });
        enteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteriActionPerformed(evt);
            }
        });
        jPanel2.add(enteri);
        enteri.setBounds(170, 190, 170, 26);

        jLabel3.setText("Insure Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 200, 103, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 70, 430, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enternActionPerformed
entern.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_enternActionPerformed

    private void entereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entereActionPerformed
entere.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_entereActionPerformed

    private void enterpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpActionPerformed
enterp.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_enterpActionPerformed

    private void enteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteriActionPerformed
enteri.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_enteriActionPerformed

    private void enternFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enternFocusLost
    if (entern.getText().isEmpty() || entern.getText().equals("")) {
        entern.setText("User name");
    }       }//GEN-LAST:event_enternFocusLost

    private void entereFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entereFocusGained
 if (entere.getText().equals("Example.com")) {
        entere.setText(""); 
    }           }//GEN-LAST:event_entereFocusGained

    private void enterpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpFocusGained
 if (enterp.getText().equals("Pasword")) {
        enterp.setText(""); 
    }       
    }//GEN-LAST:event_enterpFocusGained

    private void enteriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteriFocusGained
 if (enteri.getText().equals("Insure Pasword")) {
        enteri.setText(""); 
    }           }//GEN-LAST:event_enteriFocusGained

    private void entereFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entereFocusLost
   if (entere.getText().isEmpty() || entere.getText().equals("")) {
        entere.setText("Example,com");
    }      }//GEN-LAST:event_entereFocusLost

    private void enterpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpFocusLost
   if (enterp.getText().isEmpty() || enterp.getText().equals("")) {
        enterp.setText("pasword");
    }      }//GEN-LAST:event_enterpFocusLost

    private void enteriFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteriFocusLost
   if (enteri.getText().isEmpty() || enteri.getText().equals("")) {
        enteri.setText("Insure pasword");
    }          // TODO add your handling code here:
    }//GEN-LAST:event_enteriFocusLost

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
login x=new login();
this.dispose();
x.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void enternFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enternFocusGained
 if (entern.getText().equals("User name")) {
        entern.setText(""); 
    }           }//GEN-LAST:event_enternFocusGained

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

String p=ch.getActionCommand();

if(ch.getSelectedIndex() == 1){
       User k=new User();
k.setVisible(true);
this.dispose();}
else if (ch.getSelectedIndex() == 0){
       Admin k=new Admin();
k.setVisible(true);
this.dispose();
   }else{
      entern.setText("");
       enterp.setText("");
       enteri.setText("");
       entere.setText("");
      // enterp.setText("");


}    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ch;
    private javax.swing.JButton create;
    private javax.swing.JTextField entere;
    private javax.swing.JPasswordField enteri;
    private javax.swing.JTextField entern;
    private javax.swing.JPasswordField enterp;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signin;
    // End of variables declaration//GEN-END:variables
}
